---
# Update hosts file on host machine
- name: Add Quay FQDN entry to host machine hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ quay_ip }} {{ quay_fqdn }}"
    regexp: "^{{ quay_ip }}.*"
    state: present
  become: true
  delegate_to: localhost

# Update hosts file on Quay VM
- name: Add Quay FQDN entry to Quay VM hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ quay_ip }} {{ quay_fqdn }}"
    regexp: "^{{ quay_ip }}.*"
    state: present
  become: true
